puts ""
puts "Your probably expecting a normal performance test here, but since I had trouble"
puts "getting benchmarking to work with Authlogic, I decided to take a different approach."
puts "I've created a JMeter test plan to measure the performance of this application."
puts ""
puts "  1) Install and run JMeter"
puts "  2) Load one of the *.jmx files in the test/performance directory"
puts "  3) Configure the User Defined Variables to match your environment"
puts "  4) Run the test"
puts ""
puts "By default, I have a pretty minimal output setup but its pretty easy to add"
puts "your own graphs, charts, and whatnot.  Just take a quick view at the JMeter"
puts "website and you'll be on your way to performance testing mastery in not time."